version: "3.9"

services:
  db-postgres-back-end:
    profiles: ["local"]
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"